const churchHistoryQuestions = [
    {question: "Who is considered the founder of the Christian Church?", answer: "Jesus Christ."},
    {question: "What event is traditionally considered the birth of the Church?", answer: "The Day of Pentecost."},
    {question: "In which city were the followers of Jesus first called Christians?", answer: "Antioch."},
    {question: "Who was the first Christian martyr?", answer: "Stephen."},
    {question: "What Roman emperor legalized Christianity?", answer: "Constantine the Great."},
    {question: "What year was the Edict of Milan issued?", answer: "313 AD."},
    {question: "Which council affirmed the doctrine of the Trinity?", answer: "The Council of Nicaea."},
    {question: "Who was the first bishop of Rome (the first pope)?", answer: "Peter."},
    {question: "What event in 1054 split the Church into East and West?", answer: "The Great Schism."},
    {question: "What was the primary language of the Eastern Church after the schism?", answer: "Greek."},
    {question: "What was the primary language of the Western Church after the schism?", answer: "Latin."},
    {question: "Who wrote the '95 Theses'?", answer: "Martin Luther."},
    {question: "What movement did Martin Luther's actions start?", answer: "The Protestant Reformation."},
    {question: "What year did the Protestant Reformation begin?", answer: "1517."},
    {question: "What council was held in response to the Protestant Reformation?", answer: "The Council of Trent."},
    {question: "Who was the first Christian Roman emperor?", answer: "Constantine the Great."},
    {question: "What does the term 'apostolic succession' mean?", answer: "The unbroken line of bishops tracing back to the apostles."},
    {question: "What is the significance of the Nicene Creed?", answer: "It defines the foundational beliefs of Christianity, particularly the Trinity."},
    {question: "Who was the mother of Emperor Constantine?", answer: "Helena."},
    {question: "What is the term for the split between the Catholic Church and the Protestant denominations?", answer: "The Reformation."},
    {question: "Who translated the Bible into Latin (the Vulgate)?", answer: "Jerome."},
    {question: "What was the purpose of the Crusades?", answer: "To reclaim the Holy Land from Muslim control."},
    {question: "What year did the Great Fire of Rome occur, leading to persecution of Christians?", answer: "64 AD."},
    {question: "Who was the Roman emperor during the Great Fire of Rome?", answer: "Nero."},
    {question: "What does the term 'ecumenical council' mean?", answer: "A gathering of Church leaders to decide important theological issues."},
    {question: "Who was the first theologian to coin the term 'Trinity'?", answer: "Tertullian."},
    {question: "What is the meaning of the term 'Christendom'?", answer: "The worldwide body or society of Christians."},
    {question: "Who was the bishop of Hippo and an influential Church Father?", answer: "Augustine."},
    {question: "What is Augustine's most famous work?", answer: "The City of God."},
    {question: "What major event occurred in 1517 in Wittenberg?", answer: "Martin Luther nailed the 95 Theses to the church door."},
    {question: "What does 'Pentecost' mean?", answer: "The 50th day after Easter, when the Holy Spirit descended on the apostles."},
    {question: "Who is known as the 'Apostle to the Gentiles'?", answer: "Paul."},
    {question: "Which Roman emperor initiated the last and most severe persecution of Christians?", answer: "Diocletian."},
    {question: "What famous Christian document was written in 325 AD?", answer: "The Nicene Creed."},
    {question: "Who was the first Christian missionary to Ireland?", answer: "St. Patrick."},
    {question: "What year did the Eastern Orthodox Church and Roman Catholic Church formally split?", answer: "1054 AD."},
    {question: "What does the term 'heresy' mean?", answer: "Belief or opinion contrary to orthodox Christian doctrine."},
    {question: "What is the significance of the Council of Chalcedon (451 AD)?", answer: "It affirmed that Jesus has two natures, fully God and fully man."},
    {question: "Who was the first Christian emperor of Ethiopia?", answer: "Ezana."},
    {question: "What was the purpose of the Inquisition?", answer: "To root out and punish heresy within the Church."},
    {question: "What year did the Vatican II Council begin?", answer: "1962."},
    {question: "Who was the pope during the Second Vatican Council?", answer: "Pope John XXIII."},
    {question: "What is the largest Christian denomination in the world?", answer: "Roman Catholicism."},
    {question: "What is the name of the Church established by Henry VIII?", answer: "The Church of England (Anglican Church)."},
    {question: "Who was the leader of the Swiss Reformation?", answer: "Ulrich Zwingli."},
    {question: "What is the primary focus of the Book of Acts in the New Testament?", answer: "The early history of the Church and the spread of the Gospel."},
    {question: "What does the word 'gospel' mean?", answer: "Good news."},
    {question: "Who is traditionally regarded as the author of the majority of the New Testament letters?", answer: "Paul."},
    {question: "What is monasticism?", answer: "A religious way of life involving renunciation of worldly pursuits to devote oneself to spiritual work."},
    {question: "Who is known as the 'Father of Monasticism'?", answer: "St. Anthony of Egypt."},
    {question: "What does the term 'canon' refer to in Christianity?", answer: "The official list of books included in the Bible."},
    {question: "What event marked the beginning of the Byzantine Empire?", answer: "The founding of Constantinople in 330 AD."},
    {question: "Who was the first Christian missionary to England?", answer: "St. Augustine of Canterbury."},
    {question: "What is the significance of the Edict of Thessalonica?", answer: "It made Christianity the official religion of the Roman Empire."},
    {question: "What year was the Edict of Thessalonica issued?", answer: "380 AD."},
    {question: "What is the origin of the term 'Protestant'?", answer: "It comes from the protest of reformers against the Catholic Church."},
    {question: "Who was the leader of the Reformation in Geneva?", answer: "John Calvin."},
    {question: "What is John Calvin's most famous theological work?", answer: "Institutes of the Christian Religion."},
    {question: "What doctrine is John Calvin most associated with?", answer: "Predestination."},
    {question: "What is the significance of the Council of Trent?", answer: "It was the Catholic Church's response to the Protestant Reformation."},
    {question: "Who wrote 'Confessions', an important work in Church history?", answer: "Augustine of Hippo."},
    {question: "What is the Septuagint?", answer: "The Greek translation of the Hebrew Scriptures (Old Testament)."},
    {question: "Who convened the First Council of Nicaea?", answer: "Emperor Constantine the Great."},
    {question: "What year was the First Council of Nicaea held?", answer: "325 AD."},
    {question: "What does the term 'Great Schism' refer to?", answer: "The split between the Eastern Orthodox and Roman Catholic Churches in 1054 AD."},
    {question: "Who was the first woman declared a Doctor of the Church?", answer: "St. Teresa of Ávila."},
    {question: "What is the meaning of the word 'apostle'?", answer: "One who is sent out."},
    {question: "What is the significance of the Dead Sea Scrolls?", answer: "They provided insight into Jewish life and scripture during Jesus' time."},
    {question: "Who was the first martyr among the apostles?", answer: "James, the brother of John."},
    {question: "What is the Didache?", answer: "An early Christian document outlining Church teaching and practices."},
    {question: "What is the meaning of 'sacrament'?", answer: "A religious rite recognized as of particular importance and significance."},
    {question: "Who was the first pope to resign?", answer: "Pope Benedict IX."},
    {question: "What was the main goal of the Crusades?", answer: "To reclaim Jerusalem and the Holy Land from Muslim control."},
    {question: "Who initiated the Protestant Reformation in Switzerland?", answer: "Ulrich Zwingli."},
    {question: "What does the term 'syllogism' mean in theological arguments?", answer: "A form of reasoning in which a conclusion is drawn from two given or assumed propositions."},
    {question: "What year did the Protestant Reformation lead to the formation of the Lutheran Church?", answer: "1530."},
    {question: "What was the significance of the Council of Worms?", answer: "It addressed Martin Luther's teachings and resulted in his excommunication."},
    {question: "Who is considered the founder of the Jesuit order?", answer: "St. Ignatius of Loyola."},
    {question: "What is the significance of the term 'sola scriptura'?", answer: "It emphasizes Scripture as the sole authority in matters of faith and practice."},
    {question: "Who was the influential theologian known for his work on grace and free will?", answer: "Augustine of Hippo."},
    {question: "What is the meaning of the term 'apocrypha'?", answer: "Books excluded from the canonical Bible."},
    {question: "What is the Council of Constantinople known for?", answer: "It affirmed the Nicene Creed and dealt with Christological controversies."},
    {question: "What does the term 'schism' refer to in church history?", answer: "A division or separation in the Church."},
    {question: "Who was the influential Church Father known for his defense of Christian doctrine against heresies?", answer: "Athanasius."},
    {question: "What is the role of a bishop in the Church?", answer: "To oversee a diocese and provide spiritual leadership."},
    {question: "What is the significance of the 'Apostles' Creed'?", answer: "It summarizes the apostolic faith and serves as a declaration of belief."},
    {question: "Who wrote 'The City of God'?", answer: "Augustine of Hippo."},
    {question: "What is the significance of the Edict of Milan?", answer: "It granted religious tolerance to Christians in the Roman Empire."},
    {question: "What is an ecumenical council?", answer: "A meeting of Church leaders to discuss and resolve issues affecting the Church."},
    {question: "Who was the first Christian to be executed for their faith?", answer: "Stephen."},
    {question: "What does the term 'sacramental' refer to?", answer: "Relating to sacraments or the sacred."},
    {question: "What is the significance of the 'Nicene-Constantinopolitan Creed'?", answer: "It is a statement of faith that defines the beliefs of Christianity."},
    {question: "Who was the first Christian historian?", answer: "Eusebius of Caesarea."},
    {question: "What is the significance of the Council of Ephesus (431 AD)?", answer: "It affirmed the title of Mary as Theotokos, or 'God-bearer'."},
    {question: "What year did the Anglican Church separate from the Catholic Church?", answer: "1534."},
    {question: "What is the significance of the term 'apostolic'?", answer: "It refers to the teachings and practices originating from the apostles."},
    {question: "Who was the founder of the Methodist movement?", answer: "John Wesley."},
    {question: "What is the primary focus of the Book of Revelation?", answer: "The prophetic vision of the end times and the second coming of Christ."},
    {question: "What does the term 'inquisition' refer to?", answer: "A series of institutions within the Church aimed at combating heresy."},
    {question: "Who was the influential theologian known for his doctrine of double predestination?", answer: "John Calvin."},
    {question: "What is the significance of the term 'catholic' in relation to the Church?", answer: "It means universal, referring to the whole body of believers."},
    {question: "What is the role of the Pope in the Catholic Church?", answer: "To serve as the spiritual leader and representative of Christ on Earth."},
    {question: "What does the term 'purgatory' refer to?", answer: "A state of purification for souls before entering heaven."},
    {question: "Who was the first pope?", answer: "St. Peter."},
    {question: "What is the significance of the term 'excommunication'?", answer: "It is a formal exclusion from participation in the sacraments and services of the Church."},
    {question: "What is the meaning of the term 'soteriology'?", answer: "The study of salvation."},
    {question: "Who established the first monastic community in the West?", answer: "St. Benedict."},
    {question: "What is the significance of the 'Sermon on the Mount'?", answer: "It contains key teachings of Jesus, including the Beatitudes."},
    {question: "What does the term 'fundamentalism' refer to in a religious context?", answer: "A movement emphasizing a strict adherence to foundational beliefs."},
    {question: "What is the role of deacons in the Church?", answer: "To assist bishops and priests in serving the community."},
    {question: "Who was known for his work in biblical translation and exegesis?", answer: "Martin Luther."},
    {question: "What does the term 'theology' mean?", answer: "The study of the nature of God and religious belief."},
    {question: "What is the significance of the term 'sacramental economy'?", answer: "It refers to the way in which God's grace is communicated through the sacraments."},
    {question: "Who was the reformer known for his emphasis on justification by faith?", answer: "Martin Luther."},
    {question: "What does the term 'eschatology' refer to?", answer: "The study of end times and final events."},
    {question: "What is the significance of the 'Lutheran Confessions'?", answer: "They articulate the beliefs and practices of the Lutheran tradition."},
    {question: "Who was the first Christian emperor of Rome?", answer: "Constantine the Great."},
    {question: "What does the term 'apocalyptic' refer to?", answer: "Relating to revelation or the end of the world."},
    {question: "What is the significance of the 'Vulgate'?", answer: "It is the Latin translation of the Bible used in the Catholic Church."},
    {question: "Who was the influential Christian philosopher known for his works on faith and reason?", answer: "St. Augustine."},
    {question: "What does the term 'Trinity' refer to?", answer: "The Christian doctrine that defines God as three persons in one essence."},
    {question: "Who was the first Christian historian to write about the early Church?", answer: "Eusebius."},
    {question: "What is the significance of the 'Great Commission'?", answer: "It is Jesus' instruction to his disciples to spread the Gospel."},
    {question: "Who was the famous missionary known for his work in Africa?", answer: "David Livingstone."},
    {question: "What does the term 'liturgical year' refer to?", answer: "The annual cycle of seasons and feasts in the Christian calendar."},
    {question: "What is the significance of the 'Benedictine Rule'?", answer: "It provides guidelines for monastic life and community living."},
    {question: "Who was the first Christian to be martyred in the New Testament?", answer: "Stephen."},
    {question: "What does the term 'ecclesiology' refer to?", answer: "The study of the Church and its structure."},
    {question: "What is the significance of the 'Council of Florence'?", answer: "It aimed to reconcile the Eastern and Western Churches."},
    {question: "Who was the theologian known for his emphasis on the sovereignty of God?", answer: "John Calvin."},
    {question: "What does the term 'sacrilege' mean?", answer: "The violation or disrespect of sacred things."},
    {question: "What is the significance of the 'Age of Enlightenment' for Christianity?", answer: "It challenged traditional beliefs and encouraged rational thought."},
    {question: "Who was the influential theologian known for his contributions to systematic theology?", answer: "Charles Hodge."},
    {question: "What does the term 'theophany' refer to?", answer: "A visible manifestation of God."},
    {question: "What is the significance of the 'Council of Nicea II'?", answer: "It reaffirmed the decisions made in the First Council of Nicaea."},
    {question: "Who was the saint known for his care for the poor and sick?", answer: "St. Francis of Assisi."},
    {question: "What does the term 'heresy' mean?", answer: "A belief or opinion that deviates from established doctrine."},
    {question: "What is the significance of the 'Apostolic Fathers'?", answer: "They were early Christian writers who shaped Church doctrine."},
    {question: "Who was the first pope to live in the Vatican?", answer: "Pope Nicholas III."},
    {question: "What does the term 'council' refer to in a church context?", answer: "A formal assembly of church leaders to discuss and decide on church matters."},
    {question: "What is the significance of the 'Gnostic Gospels'?", answer: "They offer alternative views of Jesus' teachings."},
    {question: "Who was the founder of the Salvation Army?", answer: "William Booth."}
  ]
  
    module.exports = churchHistoryQuestions;